project:
  type: website
  output-dir: docs

website:
  title: "Matt Beckstrom"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Writing.qmd

format:
  html:
    theme: jolla
    css: styles.css
    toc: true



