project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-7RT2VV7DYD"
  title: "Matt Beckstrom"
  site-url: https://mattbeckstrom.com
  favicon: ./images/favicon.png
  navbar:
    logo: ./images/logo.png
    logo-alt: "MB logo"
    search: false
    background: "dark"
    right:
      - text: "Home"  
        href: index.qmd
      - text: "Writing"
        href: writing.qmd
      - text: "Presentations"
        href: presentations.qmd
      - text: "Academics"
        href: academics.qmd
      - text: "CV"
        href: file /images/cv.pdf

  page-footer:
      background: dark
      left: Copyright 2024, Matt Beckstrom
      right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/mattbeckstrom/mattbeckstrom.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    page-layout: full
    theme: solar



